function Cambiodeopciones() {

  //  let opciones = document.getElementsByName("opciones");

  //  console.log(opciones);
    
   // for(let i=0; i)     <opciones.length;i++ {

// {

console.log ("Hola mundo");
console.log ("Hola mundo");
console.log ("Hola mundo");
console.log ("Hola mundo");
console.log ("Hola mundo");

for(var x=0; x < 200; x++) {
        console.log("Hola mundo");
    }
}



// x-x + 1 == x++;